# global config
spring:
  application:
    name: one
  profiles:
    active: dev
  datasource:
    druid:
      initial-size: 20
      max-active: 150
      min-idle: 10
      max-wait: 30000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      filters: stat,wall
#quartz定时器配置
  quartz:
    properties:
      org:
        quartz:
          scheduler:
            instanceName: clusteredScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            tablePrefix: QRTZ_
            isClustered: false
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true
    job-store-type: jdbc

  jmx:
    enabled: false  #在一个tomcat里启动两个springBoot项目

# 开发过程要关闭Thymeleaf缓存
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    servlet:
      content-type: text/html
    mode: HTML5

#整合redis
  redis:
    host: localhost
   # password: redispassword
    port: 6379
    timeout: 3000 # 连接超时时间 单位 ms（毫秒）
    pool:
      max-idle: 100 # 连接池中的最大空闲连接，默认值也是8
      min-idle: 1   # 连接池中的最小空闲连接，默认值也是0
      max-active: 1000 # 如果赋值为-1，则表示不限制；如果pool已经分配了maxActive个jedis实例，则此时pool的状态为exhausted(耗尽)。
      max-wait: -1  # 等待可用连接的最大时间，单位毫秒，默认值为-1，表示永不超时。如果超过等待时间，则直接抛出





# dev config
---
spring:
  profiles: dev
  datasource:
    oracle:
        type: com.alibaba.druid.pool.DruidDataSource
#        url: jdbc:oracle:thin:@10.106.36.98:1521:rmmis2
#        url: jdbc:oracle:thin:@192.168.73.130:1521/orcl
#        url: jdbc:oracle:thin:@192.168.124.129:1521:orcl
        url: jdbc:oracle:thin:@192.168.73.128:1521:orcl
#        username: dzpb
        username: yingpin
        password: a123456


  datasource2:
    oracle2:
        type: com.alibaba.druid.pool.DruidDataSource
#        url: jdbc:oracle:thin:@10.106.36.98:1521:rmmis2
#        url: jdbc:oracle:thin:@192.168.73.130:1521/orcl
#        url: jdbc:oracle:thin:@192.168.124.129:1521:orcl
        url: jdbc:oracle:thin:@192.168.73.128:1521:orcl
        username: yingpin2
        password: a123456

server:
  port: 8888
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml #这个是你定义的mapping文件，支持通配符，如果有多个用逗号隔开。
  config-locations: classpath:mybatis-config.xml
  typeAliasesPackage: com.example.one.model #这个定义实体类所在的包名，或者其他能使用别名的类所在的包。
  configuration:
    jdbc-type-for-null: 'null' # 解决map映射不显示，null显示为""
    call-setters-on-nulls: true # 解决map映射不显示，null显示为""
    cache-enabled: false #配置的缓存的全局开关
#    lazyLoadingEnabled: true #延时加载的开关
    map-underscore-to-camel-case: false
  global-config:
#    id-type: 3  #1:数据库ID自增   2:用户输入id   3:全局唯一id(IdWorker)   4:全局唯一ID(uuid)
    db-column-underline: false
    refresh-mapper: true
#    is-capital-mode: false
logging:
  level:
    com.example.cgzbtzs.dao: DEBUG  # mybatis sql打印


